version: '2'
services:
    library-app:
        image: library
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://library-postgresql:5432/library
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://library-elasticsearch:9200
        ports:
            - 8080:8080
    library-postgresql:
        extends:
            file: postgresql.yml
            service: library-postgresql
    library-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: library-elasticsearch
